config/routes.rb
Rails.application.routes.draw do
  get 'bookings/new'
  post 'bookings/create'
  get 'booking/:id', to: 'bookings#show', as: 'booking'
  get 'about/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'flights#index'
  get '/flights', to: 'flights#index'
end

app/models/airport.rb
class Airport < ApplicationRecord
  has_many :departing_flights, foreign_key: :departure_airport_id, class_name: 'Flight'
  has_many :arriving_flights, foreign_key: :arrival_airport_id, class_name: 'Flight'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  has_many :passengers
  belongs_to :flight
  accepts_nested_attributes_for :passengers

end

app/models/flight.rb
class Flight < ApplicationRecord
  belongs_to :arrival_airport, class_name: 'Airport', foreign_key: 'arrival_airport_id'
  belongs_to :departure_airport, class_name: 'Airport', foreign_key: 'departure_airport_id'
  has_many :bookings
  has_many :passengers, through: :bookings
end

app/models/passenger.rb
class Passenger < ApplicationRecord
  belongs_to :booking
  validates :name, presence: true
  validates :email, presence: true
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :check_flight_exists, only: [:create, :new]
  before_action :check_booking_exists, only: [:show]

  def new
    @flight = Flight.find_by(id: params[:flight])
    @passenger_num = params[:passengers]
    @booking = Booking.new(flight_id: @flight.id)
    @passenger_num.to_i.times { @booking.passengers.build }
  end

  def create
    @booking = Booking.new(booking_params)
    if @booking.save
      @booking.passengers.each do |p|
        PassengerMailer.with(booking: @booking, passenger: p).booking_email.deliver_now!
      end
      respond_to do |format|
        format.html { redirect_to booking_path(@booking) }
        format.json { head :no_content }
      end
    else
      respond_to do |format|
        format.html { redirect_to '/', alert: "Booking could not be created" }
        format.json { head :no_content }
      end
    end
  end

  def show
    @booking = Booking.find(params[:id])
    @flight = Flight.find(@booking[:flight_id])
  end

  private

  def booking_params
    params.require(:booking).permit(:flight_id, passengers_attributes: [:email, :name])
  end

  def check_flight_exists
    unless Flight.find_by(id: params[:flight]) ||
      (params[:booking]) && Flight.find_by(id: params[:booking][:flight_id])
      respond_to do |format|
        format.html { redirect_to root_path, alert: "Flight not found" }
      end
    end
  end

  def check_booking_exists
    unless Booking.find_by(id: params[:id])
      respond_to do |format|
        format.html { redirect_to root_path, alert: "Booking not found" }
      end
    end
  end

end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController

  def index
    @airport_options = Airport.all.map { |airport| ["[#{airport.acronym}] #{airport.name}", airport.id] }
    @dates = Flight.select(:date).map { |date| [date.date.to_date] }
    @dates.uniq!
    @passengers = (1..4)
    if params[:departure_airport_id].present? && params[:arrival_airport_id].present? && params[:date].present? && params[:passengers].present?
      @available_flights = Flight.all.where(departure_airport_id: params[:departure_airport_id],
                                            arrival_airport_id: params[:arrival_airport_id]).where("date::date = ?", params[:date])
      @passenger_num = params[:passengers]
      unless @available_flights.count.positive? && @passenger_num.to_i.positive?
        @available_flights = nil
        respond_to do |format|
          format.html { redirect_to '/', alert: "No available flights, please check your options." }
          format.json { head :no_content }
        end
      end
    end
  end

end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/views/about/index.html.erb
<div class="about">

  <div class="column">
    <div class="box">
      <div class="columns is-centered is-vcentered is-warning">

        <div class="field is-vcentered">
          <label class="label has-text-centered"></label>
          <div class="control">
            Website built by <strong>Kostas-S</strong> as part of the Odin Project course.
            <a href="https://choosealicense.com/licenses/mit/" target="_blank">MIT License</a>, 2021.
          </div>
        </div>
      </div>
    </div>
  </div>

</div>

app/views/bookings/create.html.erb
<h1>Bookings#create</h1>
<p>Find me in app/views/bookings/create.html.erb</p>

app/views/bookings/new.html.erb
<div class="form">
  <div class="column">

    <div class="box">
      <%= form_with model: @booking, url: bookings_create_path, method: 'post', local: true do |f| %>
        <%= f.hidden_field :flight_id, value: @flight.id %>
        <div class="columns is-centered is-vcentered is-warning">
          <div class="field">
            <div class="collection">
              <div>
                <div class="is-vcentered flight">
                  <div class="title is-5 has-text-centered"><%= @flight.date.to_formatted_s(:short) %></div>

                  <span class="title is-5"><%= @flight.departure_airport.name %></span>
                  <span class="icon-text"><span class="icon">
                    <i class="fas fa-plane" aria-hidden="true"> </i>
                    </span>
                        <span class="title is-5"><%= @flight.arrival_airport.name %></span>
                    </span>
                  <br/>
                  <div class="title is-6 has-text-centered"><%= @flight.duration %>
                    minutes
                  </div>

                </div>
              </div>
            </div>
          </div>
        </div>
        <br/>



        <%= f.fields_for :passengers do |form| %>

          <div class="passenger">
            <div class="form">
              <div class="flight">
                <div class="title is-5 has-text-centered">Passenger Info:</div>
                <div class="control">
                  <%= form.text_field :name, placeholder: "Name", required: true, class: "input is-warning" %></div>
                <br/>
                <div class="control">
                  <%= form.email_field :email, placeholder: "Email", required: true, class: "input is-warning" %></div>
              </div>
            </div>
          </div>
        <% end %>


        <br/>
        <div class="is-vcentered has-text-centered">

          <%= f.submit "Book Tickets", class: "button is-dark is-rounded" %>

        </div>

      <% end %>
    </div>
  </div>

</div>

app/views/bookings/show.html.erb
<div class="form">
  <div class="column">
    <div class="box">


      <div class="field">

        <div class="collection">

          <div class="is-centered has-text-centered flight">
            <h4 class="title is-4 has-text-centered">Enjoy your trip!</h4>
            <div class="title is-5 has-text-centered"><%= @flight.date.to_formatted_s(:short) %></div>

            <span class="title is-5"><%= @flight.departure_airport.name %></span>
            <span class="icon-text"><span class="icon">
                    <i class="fas fa-plane" aria-hidden="true"> </i>
                    </span>
                        <span class="title is-5"><%= @flight.arrival_airport.name %></span>
                    </span>
            <br/>
            <div class="title is-6 has-text-centered"><%= @flight.duration %>
              minutes
            </div>
          </div>
          <br/><br/>
          <% i = 1 %>
          <% @booking.passengers.each do |passenger| %>
            <div class="is-centered has-text-centered flight">

              <div class="title is-5 has-text-centered"><strong>Passenger </strong> <%= i %></div>
              <div class="title is-4 has-text-centered"><strong>Name:</strong> <%= passenger.name %></div>
              <div class="title is-4 has-text-centered"><strong>Email:</strong> <%= passenger.email %></div>
            </div>
            <% i += 1 %>
          <% end %>
          <br/><br/>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/flights/_form.html.erb
<div class="form">

  <div class="column" id="search-form">
    <div class="box">
      <%= form_with model: @flight, url: '/flights', method: 'get', remote: true do |f| %>
        <div class="columns is-centered is-vcentered is-warning">

          <div class="field">
            <label class="label has-text-centered"></label>
            <div class="control">
              <div class="select is-rounded">
                <%= f.select(:departure_airport_id, (airport_options), prompt: "From:") %>
              </div>
            </div>
          </div>


          <div class="field">
            <label class="label has-text-centered"></label>
            <div class="control">
              <div class="select is-rounded">
                <%= f.select(:arrival_airport_id, (airport_options), prompt: "To:") %>
              </div>
            </div>
          </div>

          <div class="field">
            <label class="label has-text-centered"></label>
            <div class="control">
              <div class="select is-rounded">
                <%= f.select(:date, (dates), prompt: "Date:") %>
              </div>
            </div>
          </div>

          <div class="field">
            <label class="label has-text-centered"></label>
            <div class="control">
              <div class="select is-rounded">
                <%= f.select(:passengers, (passengers), prompt: "Passengers:") %>
              </div>
            </div>
          </div>
          <div class="field">
            <label class="label has-text-centered"></label>
            <div class="control">
              <%= f.submit "Search", class: "button is-dark is-rounded", id: "search-btn" %>
            </div>
          </div>


        </div>
      <% end %>
    </div>
  </div>

</div>

app/views/flights/_select_flight.html.erb
<div class="select-flight">
  <div class="form">

    <div class="column">

      <div class="box">
        <%= form_with model: @flight, url: bookings_new_path, method: 'get' do |f| %>
          <%= hidden_field_tag :passengers, @passenger_num %>
          <div class="columns is-centered is-vcentered is-warning">

            <div class="field">

              <div class="collection">
                <% @available_flights.each do |currflight| %>
                  <div>
                    <label class="radio is-vcentered flight" id="flight">
                      <div class="title is-5 has-text-centered"><%= currflight.date.to_formatted_s(:short) %></div>


                      <%= f.radio_button :flight, currflight.id, required: true, class: "radio" %>
                      <span class="title is-5"><%= currflight.departure_airport.name %></span>
                      <span class="icon-text"><span class="icon">
                    <i class="fas fa-plane" aria-hidden="true"> </i>
                    </span>
                        <span class="title is-5"><%= currflight.arrival_airport.name %></span>
                    </span>
                      <br/>
                      <div class="title is-6 has-text-centered"><%= currflight.duration %>
                        minutes
                      </div>

                    </label>
                  </div>
                <% end %>
              </div>
            </div>
          </div>
          <div class="column is-vcentered has-text-centered">

            <%= f.submit "Book Tickets", class: "button is-dark is-rounded" %>

          </div>

        <% end %>
      </div>
    </div>
  </div>

</div>

app/views/flights/index.html.erb
<%= render 'flights/form', airport_options: @airport_options, dates: @dates, passengers: @passengers %>

<% if @available_flights %>
  <%= render 'select_flight' %>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="content has-text-centered">
    <p>
      Website by <a href="https://github.com/kostas-s">Kostas S</a>.
    </p>
  </div>
</footer>

app/views/layouts/_navbar.html.erb
<nav class="navbar is-warning is-family-sans-serif" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <%= link_to root_path, class: 'navbar-item' do %>
      <%= image_tag "FlyNow_logo@2x.png", width: "100" %>
    <% end %>

    <a role="button" onclick="document.querySelector('.navbar-burger').classList.toggle('is-active');
      document.querySelector('.navbar-menu').classList.toggle('is-active');" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-end">
      <%= link_to "About", about_index_path, class: "navbar-item" %>

    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FlyNow</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', :defer => 'defer' %>
</head>

<body>
<%= render 'layouts/navbar' %>
<% if alert %>
  <div class="notification is-danger">
    <p class="alert"><%= alert %></p></div>
<% end %>
<%= yield %>
<br/>
<br/>
<%= render 'layouts/footer' %>
</body>
</html>